version: '3'

services: 
  pg_db:
    container_name: pg_db
    image: postgres
    ports:
      - '${POSTGRES_PORT_NUMBER}:${POSTGRES_PORT_NUMBER}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    volumes:
      - data:/var/lib/postgresql/data

  yelp_server:
    depends_on:
      - pg_db
    container_name: yelp_server
    build: .
    ports:
      - '${PORT_NUMBER}:${PORT_NUMBER}'
    command: npm run dev
    volumes:
      - .:/app
    env_file:
      - ./.env

volumes:
  data: